### ISSUE TITLE
[Idea/suggestion] Two-way integration of NLP Profiler with Feature Engine to enhance the results generated

### ISSUE THREAD

**Issue by neomatrix369** [feature-engine/feature_engine#148]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
- (option 1) Would love to integrate NLP Profiler with Feature Engine when profiling text datasets
- (option 2) Would love to integrate Feature Engine with NLP Profiler to assist generating features when working with text data

Happy to discuss this further and would love someone to point me to areas of the source code to look at, for either of these to work/to happen.

**Describe alternatives you've considered**
Contribute the functionality separately to feature engine although that would make it hard to maintain the NLP Profiler library and also Feature Engine at the same time

**Additional context**
See slides from the recent presentation to give a good idea of the project: https://bit.ly/nlp-profiler-slides

**Comment by solegalli** [comment]
@neomatrix369 thank you for the suggestion

Just had a look at the package and the presentation. Not too sure what you have in mind. 

Could you elaborate a bit more? 
how would this fit within the fit() transform() functionality we would like to keep in Feature-engine? 
Which features would be derived by the profiler? 
should we port all the scripts in the profiler repo?
how would we minimise dependencies of external libraries? 
would this make feature engine dependent of nltk and nlp-profiler?
Why do you think it is a good idea to integrate it with Feature-engine?
would this not be a better fit for a NLP package?

Thank you!

**Comment by neomatrix369** [comment]
Good questions and conjecture points, let me have a better look at your library and use it. 

Whats a good place to start you suggest, the docs and examples?

**Comment by solegalli** [comment]
yep

**Comment by neomatrix369** [comment]
Replying to your queries in between the commented lines:

> @neomatrix369 thank you for the suggestion
> 
> Just had a look at the package and the presentation. Not too sure what you have in mind.
> 
> Could you elaborate a bit more?

> how would this fit within the fit() transform() functionality we would like to keep in Feature-engine?

Maybe a `fit_transform()` function might help as NLP Profiler does not train (or do any training like action) - applies libraries directly on the data (the libraries internally may be inferring using it's own model(s))

> Which features would be derived by the profiler?

Many of the features that NLP Profiler already generates from text data (we can pick and choose relevant ones in the beginning). There are a few functionalities in the building if you see the Issues section of [NLP Profiler](https://github.com/neomatrix369/nlp_profiler/).

> should we port all the scripts in the profiler repo?

Not sure what you mean by this?

> how would we minimise dependencies of external libraries?

External libraries provide good deal of the functionality to NLP Profiler - as we are building on the top of good works of others

> would this make feature engine dependent of nltk and nlp-profiler?

Yes possible, that's why it's an idea to integrate the two together, I don't see another way without introducing complexity

> Why do you think it is a good idea to integrate it with Feature-engine?

As feature engine may be lacking some of these functionalities (low-level features from NLP Profiler) - instead of re-inventing the wheel we can re-use existing work

> would this not be a better fit for a NLP package?

An NLP package could also gain from it, I do have plans to integrate it into another NLP library of mine

**Comment by solegalli** [comment]
For the moment, we won't be going ahead with this suggestion. Thank you for the engagement!
