### ISSUE TITLE
MEstimateTargetEncoder

### ISSUE THREAD

**Issue by Tejash-Shah** [feature-engine/feature_engine#160]
Hi @solegalli,

As we know vanilla target encoding is prone to overfitting therefore I would like to suggest M-estimate target encoder to deal with high cardinality/overfitting issue as suggested in this [paper](https://dl.acm.org/doi/10.1145/507533.507538). Let me know if you are ok to add this functionality to feature-engine. Thanks!

**Comment by solegalli** [comment]
Hi @Tejash-Shah, why did you close this issue?

**Comment by Tejash-Shah** [comment]
Hi @solegalli, there was no update on this issue for a long time so thought to close it. Let me know if you want to reopen it.

**Comment by solegalli** [comment]
We are focusing on improving code, docs and including feature selection transformers for the next release in a few weeks. 

We will pick this up at some point :p   

I don't see why we should close ideas / suggestions without having a proper look :)

Sorry for not coming back earlier and thanks for the patience. I would re-open.

**Comment by Tejash-Shah** [comment]
No worries, re-opening :)

**Comment by pradumna123** [comment]
Can you elaborate on this?

**Comment by pradumna123** [comment]
Are we doing this?

**Comment by solegalli** [comment]
I have not yet had time to read the paper. So I am not deeply familiar with what this request is about, or what the transformation is intended to do. 

There are other issues that have priority at the moment. We can pick this one up later in the year?

**Comment by Tejash-Shah** [comment]
Sorry, been occupied with other tasks.  Since vanilla target encoder is prone to overfitting I want to suggest ```MEstimateEncoder``` which takes into consideration prior and posterior probabilities. There is only one hyperparameter that tells how much focus we should put on the posterior and prior probabilities. In the case of high cardinality or even category with low samples, target encoding overfits and this could be a good alternative. I rarely(almost never) use Target Encoder anyway so wanted to suggest this. There are also other variants of target encoder mentioned in the paper but they come along with more hyperparameter. It will be good to have other alternatives in the package as well since different variants of target encoder suit different tasks at hand but I wanted to start simple. Hope this helps!

**Comment by solegalli** [comment]
This transformation already exists in [category encoders,](https://contrib.scikit-learn.org/category_encoders/mestimate.html) am I correct? as per @Tejash-Shah 's previous comment. 

@TremaMiguel you mentioned including this transformer in feature-engine as well.

I am not completely sure we should bring to feature-engine transformations that already exist in category_encoders, what would be the benefit? 

I guess, you guys probably raised it, since we have the mean target encoder, then we should probably also include the Smoothing mean? Do you guys use category_encoders? why should we include it in feature-engine as well?

We need to think about this further. Open to suggestions!

**Comment by Tejash-Shah** [comment]
I agree, there's no need to re-invent the wheel. When I was reading the paper I created my own custom transformer and thought to add it to this package but later I realized a lot of transformers/encoders are available in category encoders and no need to write my own.  I would be fine dropping this feature request of MEstimateTargetEncoder.

**Comment by solegalli** [comment]
At the moment, we are not going to go ahead with introducing transformations that are available in category encoders. Instead, we linked the transformers throughout our documentation in #314 

We can re-open the issue in the future if for some reason we change our minds.
