### ISSUE TITLE
add inverse_transform to transformer classes in creation module

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#284]
The transformers in this module add new variables to the dataset with the different math operations. Inverse_transform should remove these newly created variables and return the original data representation

**Comment by NicoGalli** [comment]
@solegalli mathematical_combination.py and combine_with_reference_feature.py create new features in the dataset based in a combination of others. This meaas that "inverse" should remove those new features to obtein the original dataset. Dont think this will create to much value to this class. Any thoughts?

**Comment by NicoGalli** [comment]
@solegalli same with cyclical.py. which is also creating new features in the dataset.

**Comment by solegalli** [comment]
All transformers in this module add new variables by combining existing ones. So `inverse_transform` should just remove/drop these new variables to obtain the original dataframe representation.

I am also not sure how much value this adds to the classes.

On one hand, sklearn has `inverse_transform` in its classes (wherever possible), so to make Feature-engine more compatible, I thought we could add it to these classes as well. Code-wise, it should be fairly straightforward to implement.

One scenario could be a user wanting to understand which variables came from the raw data, and which ones were included in the engineering pipeline. But not sure how frequent this occurs.

If you want, we can leave this issue open to see if other users have some views one way or the other.

**Comment by solegalli** [comment]
@TremaMiguel in your view, would inverse_transform add any value in these classes?

**Comment by solegalli** [comment]
closing as we decided this method adds no value to the class with @NicoGalli
