### ISSUE TITLE
expand categorical detection of NAN after encoding

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#294]
At the moment, the categorical encoders will raise a warning if NAN are introduced after the encoding. This is controlled from the [BaseCategoricalEncoderClass](https://github.com/solegalli/feature_engine/blob/master/feature_engine/encoding/base_encoder.py#L155).

We should expand this warning to inform the user in which variables exactly the NaN were introduced. 

This functionality is useful in particular to help troubleshoot the SelectByTargetMean transformer.

We also need to expand the test for this class, an example [here](https://github.com/solegalli/feature_engine/blob/master/tests/test_encoding/test_count_frequency_encoder.py#L120), and make sure that all relevant categorical encoders have this check:

**Comment by solegalli** [comment]
at the back of #238

**Comment by Morgan-Sell** [comment]
I'm happy to work on the warning telling the user where the NaN exists. Please assign the task to me.

**Comment by solegalli** [comment]
Super, thank you! Go for it :)

**Comment by Morgan-Sell** [comment]
Just to confirm, the objective is to have the warning, "NaN values were introduced in the returned dataframe by the encoder..." include the names of the columns that are comprised of NaN values and to implement the corresponding unit tests. Is there anything else?

**Comment by solegalli** [comment]
The idea is to change this sentence: 
"NaN values were introduced in the returned dataframe by the encoder." 

by something like:
"NaN values were introduced in variables [list with the variable names] during the encoding."

where [list with the variable names] is the variables in which NaN were introduced. 

We need to change the error message and the code in the class so that it captures the names of the variables in which NaN were introduced.

Then, we need to expand the tests to check that the test is raised correctly and it indicates in which variable NaN were introduced.

**Comment by Morgan-Sell** [comment]
Ok, great, that's what I thought. I implemented the code. I now need to develop the unit test. I don't see a **test_base_encoder.py** file. Should I create one or add to one of the other "test_encoding" files?

**Comment by solegalli** [comment]
We would have to add 1 test in each one of the encoders :)

Also, would you mind making a PR with the code changes you already made and linking this issue?

**Comment by Morgan-Sell** [comment]
I sent the PR. Of course, I immediately noticed an error after sending the PR. The existing code does not pass the tests.

How will I know when I can send a new PR w/ the revised code?

I'll work on the tests later this week.

**Comment by solegalli** [comment]
I left a comment in the PR #338 

We follow the conversation there now that we have a PR :)

Well done with the code changes
