### ISSUE TITLE
Improve SelectByTargetMeanPerformance functionality

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#296]
Idea:

Create predictor class TargetMeanPrediction or similar name with methods fit and predict.

- Fit - learns transformation
- predict - returns the mean target value per observation

Output:

- This transformer will automatically output the mean value of the target per category if variable is categorical (we have an encoder for this). 
- If variable is numerical, it will first discretize it (we have discretizers for this, equal width and frequency, user selects) and then replace by the target mean.

The reason to create a predictor class is that then, we can use it with cross_validate and cross_val_score, in the main selector function.

Things to consider:

-  if categorical variables are highly cardinal, the encoders will introduce NaN. In issue #294 we expand the functionality to inform in which variables nan are being introduced to help user troubleshoot
- if numerical variable is highly skewed, nan can be introduced. In issue, #295 we expand the functionality to inform in which variables nan are being introduced to help user troubleshoot

Then we need to re-code the class SelectByTargetMeanPerformance to call our predictor, and use it with cross-validate to return the important features. The advantage of using corss_validate is not just the cross_validation, which offers a less biased score, but it also allows the use of other metrics, not just roc and r2 as what we have at the moment.

**Comment by solegalli** [comment]
closes #238

**Comment by SunnyxBd** [comment]
HI @solegalli , I'm thinking of picking up this issue.
what do you think?

**Comment by solegalli** [comment]
I think it is a great idea :)
I look forward to it

**Comment by SunnyxBd** [comment]
@solegalli in which folder does this predictor go? in 'creation' folder?

**Comment by solegalli** [comment]
a new one: prediction

does not exist yet :)

**Comment by SunnyxBd** [comment]
@solegalli 
I am trying to push into my branch but I am unable to do it.

remote: Permission to feature-engine/feature_engine.git denied to SunnyxBd.
fatal: unable to access 'https://github.com/feature-engine/feature_engine.git/': The requested URL returned error: 403

**Comment by Morgan-Sell** [comment]
@SunnyxBd, @solegalli 

Has this task been scooped up? ;)

**Comment by solegalli** [comment]
What do you mean? 

The basic idea is at the top of the issue.

It requires investigating the sklearn base classes that are suitable for this estimator. We need (if it exists) the equivalent of the `TransformerMixin` but for an estimator instead of a transformer.

You can get some info from the sklearn docs. Search for "building your own estimator" and "sklearn".

**Comment by solegalli** [comment]
There is a placeholder PR for this issue here #334

**Comment by Morgan-Sell** [comment]
Sorry, I'm speaking yanqui slang ;)

Is @SunnyxBd already working on this issue? I'm trying to avoid duplicate efforts.

**Comment by solegalli** [comment]
I think you are welcome to give it a go :) @Morgan-Sell
