### ISSUE TITLE
Bug in drop_last_binary of OHE

### ISSUE THREAD

**Issue by Ninimama** [feature-engine/feature_engine#301]
Hi...Thanks for creating this nice package. I think there is a potential bug with OneHotEncoder function

**Describe the bug**
The problem appears when we call `OneHotEncoder` and use `drop_last_binary=True`. According to the document, setting this argument to `True` means that for categories with two labels (binary), one of them will be eliminated as it is redundant. However, it seems it creates four new column!

**To Reproduce**
1. Get the titanic train data set and remove the `Cabin` feature. You can also impute the `Fare` with its median
2. Now we have a data set (let's call it `df_X`) with features 
<html>
<body>

Pclass | Sex | Age | SibSp | Parch | Fare | Embarked
-- | -- | -- | -- | -- | -- | --

</body>
</html>

where, `Age` is the only feature with some missing values.

3. Create the pipeline a:nd apply it to data
```
pipe_tmp = Pipeline([
    ('NA_indicator', AddMissingIndicator()),
    ('imputer', MeanMedianImputer()),
    ('encoder', OneHotEncoder(variables=['Sex'], drop_last_binary=True)),
])

pipe_tmp.fit(df_X)
df_X_new_featured = pipe_tmp.transform(df_X)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/38519522/129512718-433b2dba-d668-4256-832a-6176a29bb358.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - IDE [Jupyter Notebook]

**Comment by solegalli** [comment]
yep, that is correct. Thank you for reporting @Ninimama :)

I created a PR to address this issue asap.
