### ISSUE TITLE
Selection based on PSI values

### ISSUE THREAD

**Issue by gverbock** [feature-engine/feature_engine#307]
As a new feature, it would be nice to have a selection to remove all features having a PSI value higher than a given threshold. The Population Stability Index (PSI) is a widely used measure for population shift in a feature. If a shift has happened (i.e. if the PSI is above a given level), the feature is not fit for purpose and usually removed from the feature set.

A way to deal with it would be to have a new selector

```python
from feature_engine.selection import DropHighPSIFeatures

drop_psi = DropHighPSIFeatures(threshold=0.25)
drop_psi.fit(X_train, X_test)

X_train_adjusted = drop_psi.transform(X_train)
X_test_adjusted = drop_psi.transform(X_test)
``` 
Currently I have own implementation based on the PSI calculations from Probatus. 

Happy to pick-up the task if you believe it has added value for feature engine.

**Comment by solegalli** [comment]
Hey @gverbock thanks for the suggestion!

Would you be able to add a few links to the technique and your implementation. And give us an idea of how this method is suitable for feature selection? very briefly

I can see that it is used to measure population shifts in time. But I have not seen it used for feature selection. So I am not too sure of how it works.

Thank you!

**Comment by solegalli** [comment]
these links I found:
https://mwburke.github.io/data%20science/2018/04/29/population-stability-index.html
https://www.listendata.com/2015/05/population-stability-index.html

Wonder if you had additional ones? Ideally to an article instead of a blog

**Comment by gverbock** [comment]
Basically, the idea is to split the feature matrix according to a in-time and an out-of-time period and then perform PSI for all individual features. If a feature has a PSI above a given threshold (usually 0.25), then its distribution has shifted over time and thereby the feature is not stable. The safest approach is to exclude the feature from the feature list.

There is a paper I am aware of
https://www.bis.org/ifc/events/ws_micro_macro/nehrebecka_paper.pdf

The implementation from the PSI I use is taken from the Probatus package: https://ing-bank.github.io/probatus/api/stat_tests.html#probatus.stat_tests.psi.psi

I will ask some colleagues if they are aware of more technical articles on the use of PSI for feature selections. The information I have on that topic comes from consultancy firms and the European Central Bank but I am not allowed to share them.

**Comment by gverbock** [comment]
The (basic) implementation I have so far is the following

```pythonimport re
import pandas as pd
from probatus.stat_tests import AutoDist
from sklearn.base import BaseEstimator, TransformerMixin


def compute_PSI(train_df, test_df, bin_strategy=["SimpleBucketer", "QuantileBucketer"], n_bins=10):
        """Compute the PSI.

        Args:
            train_df (pd.DataFrame): Reference feature dataframe to compute the PSI.
            test_df (pd.DataFrame): Feature dataframe to compare to the reference.
            bin_strategy (string): Approach used to define the bins for the feature distribution.
                SimpleBucketer (default) relates to equally spaced bins and is the approach recommended
            by model validation in their Minimum Standards.
            n_bins (int): Number of bins for the distribution. 10 is recommended by Model Validation
            in their Minimum Standards.
            
        Returns:
            psi (pd.DataFrame): Dataframe with the PSI values.
            max_psi (pd.DataFrame): Dataframe with the max PSI by feature.
        """
        # Initiate the AutoDist class from Probatus
        psi_calculator = AutoDist(statistical_tests=["PSI"], binning_strategies=bin_strategy, bin_count=n_bins)
        # Compute the PSI for each feature independently.
        psi = psi_calculator.compute(train_df, test_df)
        
        # Keep only columns with PS values.
        psi_columns = [re.findall(r'statistic.*', col)[0] for col in psi.columns if re.findall(r'statistic.*', col)]
        features = psi['column']
        psi = psi[psi_columns]
        
        # Take the maximum value of the PSI's.
        max_psi = pd.DataFrame(psi.max(axis=1)).set_index(features)
        max_psi.columns = ['max_value']
        
        return psi, max_psi
    
    
class PSISelector(BaseEstimator, TransformerMixin):
    """Select features with PSI below a given threshold.
    
    Make use of the fit and transform methods so that it can be integrated in a skleanr pipeline.
    
    Args:
        threshold (float): Maximum value allowed for the PSI.
        bin_strategy (list): List of binning strategies. See Probatus for more details.
        n_bins (int): Number of bins for the bucketing.
            
    Attributes:
        psi (pd.DataFrame): DataFrame with the PSI values for the different settings.
        max_psi (pd.DataFrame): Maximum PSI for each feature.
        selected_features (list): Features having a PSI below the threshold.
    """
    
    def __init__(self,threshold, bin_strategy=['SimpleBucketer', 'QuantileBucketer'], n_bins=10):
        # Define the settings
        self.bin_strategy = bin_strategy,
        self.n_bins = n_bins
        self.threshold = threshold
        
        
    def fit(self, df_ref, df_comp):
        """Perform the PSI calculations.
        
        Args:
            df_ref (pd.DataFrame): Reference dataframe for the PSI calculations (usually train set).
            df_comp (pd.DataFrame): Dataframe for which the features are compared to the reference.
            
        Returns:
            self (object).
        """
 
        # Compute the PSI
        self.psi, self.max_psi = compute_PSI(df_ref, df_comp, self.bin_strategy[0], self.n_bins)
        
        # Select features below the threshold
        self.selected_features =self.max_psi[self.max_psi.max_value < self.threshold].index.to_list()
           
        
        return self
        
    def transform(self, df):
        """Apply the PSI filter.
        
        Args:
            df (pd.DataFrame): Dataframe with all features.
            
        Returns:
            (pd.DataFrame): Dataframe with only the selected features
        """
        
        return df[self.selected_features]
```

**Comment by solegalli** [comment]
Thank you for the links and the details @gverbock 

Feature selection transformers in Feature-engine work as follows:

1. they either take X and y in fit, so the selection method involves the target, for example in RecursiveFeatureElimination, i.e., `selector.fit(X, y)`
2. they take only X, and then select features based on some internal characteristics, for example if they are constant or they are correlated: `selector.fit(X)`

To keep the library compatible with sklearn, the method fit can only take X or X and y. But we can't pass 2 dataframes as with your implementation.

From a quick read at the links, I understand that this method will take a dataframe, separate it into 2 pieces based on dates, and then compare the PSI of the featurebetween these 2 smaller dataframes. And then select the feature based on the PSI value. **Is this correct?**

If so, we can ask the user to pass the date at which we should split the dataframe in the init (when they initialise the transformer) and then in fit, they only pass X, and the functionality splits the data based on the entered parameter.

Another important thing is that we can't make Feature-engine dependent of libraries like probatus. So we would have to implement the code to calculate the PSI from scratch (unless it is already part of a library like scipy.stats).

would you be happy with this?

**Comment by gverbock** [comment]
I fully understand the need to be consistent. This makes feature_engine so nice to work with. I would be happy with the approach you proposed. 

And yes you are correct in your understanding of how the PSI works.

**Comment by solegalli** [comment]
Great! Thanks for the feedback.

If you'd like to give it a go at drafting a first version of the code and making a PR, we would be more than happy to have your contribution :)

**Comment by gverbock** [comment]
I will do so.

**Comment by gverbock** [comment]
@solegalli Dear Soledad, I was wondering if you had time to look at the PR already. I know there is still work to do but I would like to have you opinion on the current work before going further. 
Thanks in advance for the support.

**Comment by solegalli** [comment]
I don't see any PR associated to this issue. Did you make one?

**Comment by gverbock** [comment]
I made one indeed 
![image](https://user-images.githubusercontent.com/32060943/135144738-61d25a42-739f-4a49-a918-17d350e06a41.png)
But I guess it is at the wrong place!
