### ISSUE TITLE
Adjust variables when piling up selectors

### ISSUE THREAD

**Issue by gverbock** [feature-engine/feature_engine#309]
**Is your feature request related to a problem? Please describe.**
The variables argument works very well when having a single selector but then "piling up" selectors in a pipeline it does not account for the features removed in the previous steps.

For example if I want to have the pipeline running on only variables starting with "f_" I cannot run the following code because "f_A" is not defined anymore at the second step.

![image](https://user-images.githubusercontent.com/32060943/133468023-1e0059d4-7a1b-495d-98b9-e1c731398f29.png)

Removing the variables in the second selector does not help as the feature called 'E' is also removed

![image](https://user-images.githubusercontent.com/32060943/133469287-5c3a1ba4-412b-4fd2-945e-20048339164f.png)

**Describe the solution you'd like**
I believe a selection at the beginning of the fit method would allow this feature. Something like:
```
if self.variables:
      self.variables = [var for var in self.variables if car in X.columns]
``` 

**Describe alternatives you've considered**
The alternative is to make the selection at the entry of the pipeline. Although, to me, this is not optimal as most dataframes do not only contain the features but also additional information needed further (could be a target or groups not used for modelling but for analysis).

**Comment by solegalli** [comment]
So basically, variables would have to be a subset of the variables entered by the user. Only those that are present in the input dataframe.

Makes sense. I see the problem. 

We could add a parameter in the init, confirm_variables=False, that when true runs the functionality you mention during fit.

Doable. Would you like to try? @gverbock

**Comment by gverbock** [comment]
@solegalli Happy to try this indeed. Would be in the beginning of 2022.
