### ISSUE TITLE
DropMissingData based on Percentage of Empty Columns

### ISSUE THREAD

**Issue by kevinkurek** [feature-engine/feature_engine#319]
Hi guys,

Often I find I only want to drop data if X% of the columns are missing, rather than if any data is missing.
Here is a quick demo of a compatible sklearn transformer:

    class DropThreshPct(BaseEstimator, TransformerMixin):
        """
        Keeps rows that have at least thresh_pct columns of data available.
        """
        def __init__(self, thresh_pct):
            self.thresh_pct = thresh_pct
        def fit(self, X, y=None):
            return self
        def transform(self, X):
            X.dropna(thresh=X.shape[1]*self.thresh_pct, inplace=True)
            return X

    # only returns rows that have 90% or more of columns available
    X = DropThreshPct(0.9).transform(X)

The important part being:

    X.dropna(thresh=X.shape[1]*self.thresh_pct, inplace=True)

Thoughts are to add the functionality to transform method inside imputation.DropMissingData()

    def transform(self, X: pd.DataFrame) -> pd.DataFrame:
        """
        Remove rows with missing values.
        Parameters
        ----------
        X: pandas dataframe of shape = [n_samples, n_features]
            The dataframe to be transformed.
        Returns
        -------
        X_transformed: pandas dataframe
            The complete case dataframe for the selected variables, of shape
            [n_samples - rows_with_na, n_features]
        """

        X = self._check_transform_input_and_state(X)

        X.dropna(axis=0, how="any", subset=self.variables_, inplace=True)

        return X

Would add:

class init

    param: thresh_pct: Optional[float]=None
    type: float
    raises: TypeError if thresh_pct is not type float
    raises: ValueError if thresh_pct is not between 0.0 and 1.0

transform

    if thresh_pct:
        X.dropna(thresh=X.shape[1]*self.thresh_pct, axis=0, inplace=True)
    else:
        X.dropna(axis=0, how="any", subset=self.variables_, inplace=True)

**Comment by solegalli** [comment]
added in #321
