### ISSUE TITLE
include code coverage

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#323]
At the moment, we have no visibility of test coverage. I would like to include this in the package.

Here some useful links I gathered:

https://gist.github.com/dnozay/5b9b818ff0dc857d1358

https://pytest-cov.readthedocs.io/en/latest/tox.html

https://coverage.readthedocs.io/en/6.1.1/config.html

Also check imbalanced-learn package, they have some code to run coverage.

**Comment by Morgan-Sell** [comment]
Hola @solegalli,

I'm going to git this PR a try. I need to work on my dev skills. This seems like a great place to focus!

**Comment by solegalli** [comment]
Sounds good @Morgan-Sell 

Shouldn't be too difficult (she said, :p)

Thank you!

**Comment by Morgan-Sell** [comment]
Closed by #504.
