### ISSUE TITLE
Request: add indicator variables as output from `Winsorizer`

### ISSUE THREAD

**Issue by david-cortes** [feature-engine/feature_engine#329]
**Is your feature request related to a problem? Please describe.**
When clipping extreme values in data, oftentimes having an indicator of whether a feature ended up being clipped or not turns out to be a helpful feature. Currently, `Winsorizer` will clip the features and output them with the same name, but does not produce indicator variables.

**Describe the solution you'd like**
Would be nice if `Winsorizer` had an option `add_indicator_variables` that would additionally output 0/1 variables indicating whether each of the input columns was clipped towards each side in the output transformation or not.

**Comment by solegalli** [comment]
Sounds like a good idea. We could do that. 

The code implementation is fairly straightforward. Would you like to give it a go?

The only 1 thing to consider is that the outlier trimmer inherits from the winsorizer, and we probably do not want this parameter in the trimmer, so need to think how to go about this.

A suggestion would be to create a base class with the basic functionality (i.e., how to detect the outliers). Then both transformers (Winsorizer and trimmer) inherit from this base class. And we add the additional parameter to the winsorizer.

**Comment by david-cortes** [comment]
Ok, will send a PR later this week.
