### ISSUE TITLE
dropping input columns in CombineWithReferenceFeature

### ISSUE THREAD

**Issue by kylegilde** [feature-engine/feature_engine#331]
In CombineWithReferenceFeature, would you consider adding a boolean parameter indicating whether the variables_to_combine and reference_variables columns should be dropped? 

drop_inputs=True/False

**Comment by solegalli** [comment]
We certainly could. 

In fact, we have that functionality already in the CyclicalTransformer, see this [line of code](https://github.com/feature-engine/feature_engine/blob/main/feature_engine/creation/cyclical.py#L145).

We could extend both the CombineWithReference and the MathCombinator. The changes are fairly straitghtforward. 

Would you like to give it a go?

**Comment by kylegilde** [comment]
That does seem straightforward. 

I'll take a look at your [contributor guide ](https://feature-engine.readthedocs.io/en/latest/contribute/index.html)and maybe give it a shot. 

Thanks!

**Comment by solegalli** [comment]
Great! I look forward to it.

Check this [contribute guide](https://feature-engine.readthedocs.io/en/pydata_template/contribute/index.html) instead. There is more detail in it and it will be released in the next round.
