### ISSUE TITLE
time series forecasting: lag features

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#342]
This would be a transformer that lags features (pandas.shift())

The transformer would lag all numerical features or those entered by the user, and automatically concatenate them to the df. 
Option to drop the original variables.

To think about: can we make multiple lags within one transformer? lag 1hr, lag2hrs etc, or would it be better to pile up 3 transformers instead?

The previous could be very easily done with a Pipeline, so maybe no need to overcomplicate the class.

```
# Move forward 24 hrs.
tmp = data[variables].shift(freq='24H')

# Rename the variables.
tmp.columns = [v + '_lag_24' for v in variables]

# Add the features to the original data.
data = data.merge(tmp, left_index=True, right_index=True, how='left')
```

**Comment by Morgan-Sell** [comment]
Hola @solegalli,

Per your recommendation, I'll crawl before I walk. I'll start with this issue :)

**Comment by solegalli** [comment]
Look forward to it  :)

 @Morgan-Sell
