### ISSUE TITLE
time series forecasting: window features

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#343]
The transformer should create computations over windows of past values of the features, and populate them at time t, t being the time of the forecast.

It uses pandas rolling, outputs several comptutations, mean, max, std, etc, and pandas shift to move the computations to the right row.

```
tmp = (data[variables]
       .rolling(window='3H').mean()  # Average the last 3 hr values.
       .shift(freq='1H')  # Move the average 1 step forward
       )

# Rename the columns
tmp.columns = [v + '_window' for v in variables]

data = data.merge(tmp, left_index=True, right_index=True, how='left')
```

**Comment by Morgan-Sell** [comment]
Hi @solegalli,

I'm considering taking on this issue. Which family - e.g., discretisation and encoding - will this class belong to? Or, will we create a new one?

Will this transformer be applied to all numerical columns in the provided dataframe? I guess we should check to see which columns are numerical.

**Comment by solegalli** [comment]
I recommend to start with the lagged features issue. It is simpler. 

It would go in a new module: **timeseries**. And inside that a submodule: **forecasting**

The same is true for the lagged features transformer.

**Comment by Morgan-Sell** [comment]
Hi @solegalli,

I'm happy to continue working on the time-series module or work on issue #303. Let me know what you think!

**Comment by solegalli** [comment]
Hi @Morgan-Sell 

Sure. We'll have @KishManani supporting on this issue as well.
