### ISSUE TITLE
SklearnTransformerWrapper: cross-validation error when wrapping OneHotEncoder

### ISSUE THREAD

**Issue by noahjgreen295** [feature-engine/feature_engine#368]
**Describe the bug**
I am finding that when I create an sklearn [Pipeline](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html) that uses the [SklearnTransformerWrapper](https://feature-engine.readthedocs.io/en/0.6.x_a/wrappers/Wrapper.html)  to wrap a [OneHotEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html), I get the following error when trying to [run cross-validation](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html):

```
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
...
9 fits failed out of a total of 10.
The score on these train-test partitions for these parameters will be set to nan.

Below are more details about the failures:
...
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```
If I do things the "old way" with an sklearn [ColumnTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html), I do not get the error.
I also don't get errors if I either: A) Score [without cross-validation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html) or B) Don't use the categorical features (i.e. remove the one-hot encoding).

**To Reproduce**
See code at end 

**Expected behavior**
Cross-validation should run correctly without `nan`.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version: Python 3.9.7, sklearn 1.0.1, feature-engine 1.2.0

**Additional context**
Code was copied from notebook since I could not attach it, sorry for any strange structure
**Note**: I am not doing train/test separation, in order to keep the question shorter.
**Note**: I [posted on StackOverflow](https://stackoverflow.com/questions/70931714/feature-engine-cross-validation-gives-error-when-wrapping-onehotencoder-in-skle) as well. I can remove the post if you think it's redundant - thanks!

**Code**
```
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from feature_engine.wrappers import SklearnTransformerWrapper
from feature_engine.selection import DropFeatures
from sklearn.compose import ColumnTransformer

# Sample Data
n = 20000
df = pd.DataFrame({
    "a": [["alpha", "beta", "gamma", "delta"][np.random.randint(4)] for i in range(n)],
    "b": [np.random.random() * 100 for i in range(n)],
    "c": [np.random.random() * 200 for i in range(n)],
    "d": [["east", "west"][np.random.randint(2)] for i in range(n)],
})

def make_y(x):
    add_1 = 100 if x.a in ["alpha", "beta"] else 200
    add_2 = 100 if x.d in ["east"] else 300

    return 2*x.b + 3*x.c + 2*add_1 + 5*add_2 + np.random.normal(10)

df["y"] = df.apply(make_y, axis=1)

# Test function for reproducing error
def do_test(df, pipeline, cv=True):
    X = df.drop(columns=["y"])
    y = df[["y"]]
       
    if cv:
        return cross_val_score(pipeline, X, y, scoring="neg_mean_squared_error", cv=10)
    else:
        pipeline.fit(X, y)
        y_pred = pipeline.predict(X)        
        return mean_squared_error(y, y_pred)


# SklearnTransformerWrapper-based Pipeline structure where cross-validation fails
# Will run correctly if categoricals remove, or validate on entire test set (see comments below)
pipeline_new = Pipeline(steps=[
    ("scale_b_c", SklearnTransformerWrapper(
            transformer=StandardScaler(), 
            variables=["b", "c"]
        )
    ),
    
    # Comment out this step for cross-validation to not fail
    ("encode_a_d", SklearnTransformerWrapper(
            transformer=OneHotEncoder(drop="first", sparse=False), 
            variables=["a", "d"]
        )
    ),
    
    ("cleanup", DropFeatures(["a", "d"])),
    ("model", LinearRegression())
])

# Old-style Pipeline with ColumnTransformer that works correctly:
pipeline_old = Pipeline(steps=[
    (
        "xform", ColumnTransformer([
            ("cat", OneHotEncoder(drop="first"), ["a", "d"]),
            ("num", StandardScaler(), ["b", "c"])
        ])
    ),
    ("model", LinearRegression())
])

# Run only this line to see new Pipeline issue (and comment out other do_test())
# Set cv to False to successfully score entire training set
do_test(df, pipeline_new, cv=True)

# Run only this line to see old Pipeline run correctly (and comment out other do_test())
#do_test(df, pipeline_old, cv=True)
```

**Comment by bmreiniger** [comment]
I think we've likely identified the problem in the stackexchange post.  I think either setting the index to match the original when framifying the `OneHotEncoder`'s output, or using `ignore_index=True` in the subsequent concatenation, could work.  
https://github.com/feature-engine/feature_engine/blob/e97bd4b38458ff38bd8867fe877e53c100a51a7a/feature_engine/wrappers/wrappers.py#L157

**Comment by solegalli** [comment]
Interesting. Thanks for bringing this up. 

If there is a problem with the concatenation, then other transformers that concatenate features might also have the same issue when doing cross-validation :_(

Would you like to make a PR with the proposed changes? 

We probably need to add a test with similar code to the one you have here, that fails with the current implementation, and then it should pass with the changes.

**Comment by noahjgreen295** [comment]
I would like to help! Let me work to get dev environment set up and try to block out some time to work on this.

**Comment by bmreiniger** [comment]
I can probably help if Noah doesn't have time.

I did a check for `pd.concat` issues elsewhere.  I can't promise this is exhaustive, and I haven't completed a check whether issues arise, but here's a start.

In [Winsorizer](https://github.com/feature-engine/feature_engine/blob/e97bd4b38458ff38bd8867fe877e53c100a51a7a/feature_engine/outliers/winsorizer.py#L139), I think it's fine because the things being concatenated are produced by frame operations on a common origin frame, so their indices should match.  Similar story for [target mean selection](https://github.com/feature-engine/feature_engine/blob/8e61bb4bd6aa25099d345806f2241b01923da1ea/feature_engine/selection/target_mean_selection.py#L239).

In most (all?) of the encoders (e.g. [probability_ratio](https://github.com/feature-engine/feature_engine/blob/e97bd4b38458ff38bd8867fe877e53c100a51a7a/feature_engine/encoding/probability_ratio.py#L165), [woe](https://github.com/feature-engine/feature_engine/blob/e97bd4b38458ff38bd8867fe877e53c100a51a7a/feature_engine/encoding/woe.py#L147)), there's an issue when `X` has become an array (e.g. due to an earlier sklearn step in a pipeline) but `y` remains a series.  We caught that same issue in https://github.com/scikit-learn-contrib/category_encoders/issues/280; the example there needs a little update to avoid correctly raising an error for `log(0)`, but it seems to indeed be a problem.

**Comment by noahjgreen295** [comment]
Sorry for delayed start! Starting on it today.

**Comment by solegalli** [comment]
No worries at all. We welcome all the help that we can get, whenever we can get it ;)

**Comment by noahjgreen295** [comment]
Thanks! Quick update: can't reproduce the issue in the new environment I set up (working on this at home instead of my work computer so that I can contribute from it). Comparing library versions, stepping thru with debugger, etc. Will update again once I get it reproduced and fixed.

**Comment by noahjgreen295** [comment]
Hi - I completed both the unit test and the fix for the `SklearnWrapper` issue, and am ready to submit! Happy to help on the other encoder issues @bmreiniger mentioned; should I make them part of this PR or submit this PR now and start a new one?

**Comment by solegalli** [comment]
Hi @noahjgreen295 

Sounds great. You need to upload the changes to your repo in a new branch. And from there, make a PR to this repo (a new one yes). 

This conversation here is on an issue. We can't add code here as far as I know.

Cheers

**Comment by noahjgreen295** [comment]
OK PR is [here](https://github.com/feature-engine/feature_engine/pull/375)!
I followed all instructions including using isort, black, and tox, but am still getting an error on one of the style checks.

**Comment by noahjgreen295** [comment]
> I can probably help if Noah doesn't have time (or just needs an extra hand).
> 
> I did a check for `pd.concat` issues elsewhere. I can't promise this is exhaustive, but here's a start.
> 
> In [Winsorizer](https://github.com/feature-engine/feature_engine/blob/e97bd4b38458ff38bd8867fe877e53c100a51a7a/feature_engine/outliers/winsorizer.py#L139), I think it's fine because the things being concatenated are produced by frame operations on a common origin frame, so their indices should match. Similar story for [target mean selection](https://github.com/feature-engine/feature_engine/blob/8e61bb4bd6aa25099d345806f2241b01923da1ea/feature_engine/selection/target_mean_selection.py#L239).
> 
> In most (all?) of the encoders (e.g. [probability_ratio](https://github.com/feature-engine/feature_engine/blob/e97bd4b38458ff38bd8867fe877e53c100a51a7a/feature_engine/encoding/probability_ratio.py#L165), [woe](https://github.com/feature-engine/feature_engine/blob/e97bd4b38458ff38bd8867fe877e53c100a51a7a/feature_engine/encoding/woe.py#L147)), there's an issue when `X` has become an array (e.g. due to an earlier sklearn step in a pipeline) but `y` remains a series with a nonstandard index. We caught that same issue in [scikit-learn-contrib/category_encoders#280](https://github.com/scikit-learn-contrib/category_encoders/issues/280); the example there needs a little update to avoid correctly raising an error for `log(0)` here, but it seems to indeed be a problem.
> 

Thanks again for guiding me through the process. Happy our fix is now merged!
In terms of what @bmreiniger mentions above, would you like me to help on that - starting a separate issue and PR?
