### ISSUE TITLE
Timeseries forecasting: Expanding window features

### ISSUE THREAD

**Issue by KishManani** [feature-engine/feature_engine#386]
Creating window features with an expanding rather than rolling window (see https://github.com/feature-engine/feature_engine/pull/380#issuecomment-1062057682).

@Morgan-Sell and @solegalli I have already picked this up and will tag you when ready, thanks!

**Comment by KishManani** [comment]
@Morgan-Sell and @solegalli. I've got a WIP branch here: https://github.com/KishManani/feature_engine/commit/a2d061a269e4da67fd11284f4d30811a30774faf. I rebased from the current PR of window features https://github.com/feature-engine/feature_engine/pull/380 mainly to get access to the `BaseForecast` class. Other then that they should be pretty independent. I refactored some of the tests and simplified things which could be relevant for the tests for `WindowFeatures`. I'll try and leave some comments there. Once https://github.com/feature-engine/feature_engine/pull/380 is done I will rebase and create a PR for `ExpandingWindowsFeatures`.

**Comment by solegalli** [comment]
I saw your comments on the windows features PR, very useful thank you! I will try and bring them in during this week.

Could you make a PR to this repo from your expanding windows branch? so we keep the conversation in feature-engine's main repo? You can add [WIP] if you'd prefer us to wait with the review. 

I look forward to the new class :)
