### ISSUE TITLE
extend DatetimeFeatures to extract features from index as well

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#397]
Hey @dodoarg 

Since you created this transformer, I thought I would run this issue by you, in case you have some time in your hands and would be interested in this small addition to its functionality.

The idea is that the parameter `variables` in the init, also takes the string `"index"` as input, and then extracts the datetime features from the index, which should be datetime of course.

It is common in time series data to have the datetime variable in the index of the df. And we are rolling out a new module on time series forecasting in the next release. Hence, the addition :)

Hope you are doing well otherwise!

**Comment by dodoarg** [comment]
Hi! Nice to hear from you.
I think I got what the requested functionality is. I have just landed a full time job so I'm not sure how long it'll take me but I can have a look into this yea

**Comment by solegalli** [comment]
Congratulations @dodoarg !

Your employer is lucky to have you :)
