### ISSUE TITLE
get_feature_names_out does not work with the pipeline 

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#402]
I think this is because the pipeline passes by default `input_features`, and not all transformers allow the parameter input_features at the moment. 

We need to fix this and add a couple of tests to ensure it works with the pipeline.

Hey @janrito @hectorpatino 

I would really appreciate if you could help me fix it :)

**Comment by particle1331** [comment]
The issue #403 that I just opened is related to this! I tried creating a pipeline with one hot encoder but kept getting `nan` in `cross_val_score` function of scikit-learn.

**Comment by solegalli** [comment]
The `get_feature_names_out functionality` is not released yet. So unless you are using Feature-engine's version from the main branch in this repo, this should not trigger your error.

Issue #403 does not mention anything about getting nan. Could you create a separate issue to report the potential bug and copy and paste the code that is triggering the error please?

**Comment by solegalli** [comment]
@Morgan-Sell

I need help with this issue, because we need to resolve it before launching version 1.3

The idea is that now, all classes have the method `get_feature_names_out()` that return the name of the features in the transformed dataset. That is, the dataset that results of applying the transform() method.

A bunch of those methods in the classes take no input. That makes the method not compatible with the Scikit-learn pipeline.

So basically, we need to go, class per class, and for those where the `get_feature_names_out` takes no input, we need to modify it so that it can take the parameter `input_features` which should default to None. This parameter should have no function through (we need to make this clear in the docstrings), but we need it to default to None to make it compatible with the pipeline.

Silly I know.

One thing to notice, if the class itself does not have a `get_feature_names_out`, it is because it is inheriting the functionality from the parent class. So actually, it is not as difficult as it looks.

Would you mind?

**Comment by Morgan-Sell** [comment]
hola @solegalli, me encargo!

It seems straightforward; although, scoping code is frequently deceiving ;)
