### ISSUE TITLE
DropFeatures fails when features_to_drop is a string 

### ISSUE THREAD

**Issue by noahjgreen295** [feature-engine/feature_engine#406]
**Describe the bug**
`DropFeatures` [type hint and documentation says](https://feature-engine.readthedocs.io/en/1.2.x/api_doc/selection/DropFeatures.html#:~:text=Parameters,from%20the%20dataframe) `features_to_drop` can take `str or list` as parameter, but instantiation fails when `features_to_drop` is a string.

**To Reproduce**
`transformer=DropFeatures(features_to_drop="some_string")`

**Expected behavior**
`DropFeatures` should instantiate successfully and drop the single feature specified by the string name when `transform()` or `fit_transform()` is called.

**Screenshots**
Error message:
`ValueError: features_to_drop should be a list with the name of the variablesyou wish to drop from the dataframe.`

**Additional context**
This is a simple fix, I am happy to take care of it. For convenience I would also convert the string to a single-element list when storing the attribute, for consistency.

**Comment by solegalli** [comment]
Thank you!

**Comment by noahjgreen295** [comment]
no prob, on it now!

**Comment by noahjgreen295** [comment]
OK, PR #407 here!
