### ISSUE TITLE
add function to check that y is binary in dataframe_checks

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#413]
Many transformers in feature engine require that y is binary. At the moment we do this check within each transformer. We should create a function that unifies this behaviour and call it from the transformers instead of repeating all the logic every time.

Example: encoders woe, pratio

**Comment by Morgan-Sell** [comment]
hola @solegalli,

This check will be very useful! I'll work it on. Hopefully, it will be ready for you to review once you return from vacay ;)

**Comment by Morgan-Sell** [comment]
Closed by #484

**Comment by solegalli** [comment]
> 

Actually, PRatio will be deprecated, so the only transformer atm using binary classifcation exclusively is WoE. 

Not worth the effort.
