### ISSUE TITLE
`CountFrequencyEncoder` could output zeros for new categories

### ISSUE THREAD

**Issue by david-cortes** [feature-engine/feature_engine#417]
The `CountFrequencyEncoder` has an `errors` argument which can either raise an error or output NaNs when encountering new categories. For this particular class, it'd make sense (perhaps even as a default behavior) to output zeros when a new category is encoded instead of generating NaNs.

**Comment by solegalli** [comment]
Thank you for the suggestion @david-cortes 

I see the logic of returning zeros on unseen categories, and would he happy to have that implemented. 

Not sure that I would make that the default implementation, though. I still prefer the default to alert the user that some categories were not seen (with an error). This is particularly useful for less experienced data scientists who may not be aware that this is a risk or something to consider.

Would you like to give it a go?

**Comment by david-cortes** [comment]
Ok, I'll submit a PR later, perhaps towards the end of this month.
