### ISSUE TITLE
one hot encoder of frequent categories should capture top categories with similar number of observations

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#426]
At the moment the OHE will create binary variables for the top k categories with most observations. However, if 2 categories should have similar number of observations, only 1 of them will be encoded and the other one ignored. We probably want to encode both?

**Comment by BromleyJames** [comment]
Hi @solegalli , I want to attempt this as my first issue, but I'm a little confused as to what is needed here.

Are you talking about the case where k=2 categories, in which case we have only 1 binary output?

e.g. current state

| Input | Encoding_1_green |
|------| ----------|
| green | 1 |
| green | 1 |
| green | 1 |
| green | 1 |
| green | 1 |
| blue | 0 |
| blue | 0 |
| blue | 0 |
| red | 0 |

e.g. desired state

| Input | Encoding_1_green | Encoding_2_blue |
|------| ----------| ----------|
| green | 1 | 0 |
| green | 1 | 0 |
| green | 1 | 0 |
| green | 1 | 0 |
| green | 1 | 0 |
| blue | 0 | 1 |
| blue | 0 | 1 |
| blue | 0 | 1 |
| red | 0 | 0 |

**Comment by solegalli** [comment]
The OHEEncoder has the parameter top_categories, that if set to 3 for example, the encoder will count the number of observations per category, order them from those with most to those with less categories, and then select the top 3.

So if the variable City has the following categories: London, Berlin, Manchester, Amsterdam, Buenos Aires, it will count the number of observations in each city, and select the top 3.

Now say the following happens:

- London 10 observations
- Berlin 9 observations
- Manchester 8 observations
- Amsterdam 7 observations
- Buenos Aires 6 observations

then the encoder will encode only London, Berlin and Manchester, and that should be fine. This is the current functionality.

Now if the following happens:

- London 10 observations
- Berlin 9 observations
- Manchester 8 observations
- Amsterdam 8 observations
- Buenos Aires 6 observations

The encoder will only encode London, Berlin and Manchester, even though Amsterdam also has 8 observations, just like Manchester, So the selection of the 2 cities here is kind of random. This is also the current functionality, and what I think needs to be fixed in this PR.

The correct functionality should be that the transformer picks London, Berlin, Manchester and Amsterdam for a situation like this.

Does this make sense?

**Comment by solegalli** [comment]
Btw, welcome to the project @BromleyJames 

Where did I leave my manners?

**Comment by BromleyJames** [comment]
Hi @solegalli, thank you very much for your clarifying explanation and for the warm welcome. I feel that this is much clearer now and I look forward to trying to tackle the issue.

**Comment by solegalli** [comment]
FYI @GLevV 

Closing after your suggestion that it complicates more than it helps.

Thanks for your engagement!
