### ISSUE TITLE
`OrdinalEncoder` could output -1 for unseen categories

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#428]
The OrdinalEncoder has an errors argument which can either raise an error or output NaNs when encountering new categories. For this particular class, it'd make sense to output -1 when a new category is encoded instead of generating NaNs.

**Comment by datacubeR** [comment]
@solegalli I was taking a look at this Issue and I noticed `transform` method is inherited from `CategoricalMethodsMixin`. So in order to fix this, a whole transform method should override the one in `CategoricalMethodsMixin`? Or is there a better way to do this?

**Comment by solegalli** [comment]
We did this for the CountEncoder already. I think the best would be to have a look at how we implemented there?
