### ISSUE TITLE
`CountFrequencyEncoder` could have a parameter to group categories with few observations

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#429]
Useful to handle rare categories in highly cardinal variables.

If a category is present in less than a certain threshold of observations it should be replaced by a certain value. Check page 91 of Alice Zhengs book and the CountEncoder from category encoders.

**Comment by SangamSwadiK** [comment]
Hey, @solegalli, I would like to work on this issue if possible.

**Comment by solegalli** [comment]
Great! Go for it!

Do you have an idea of how to go about it? or shall we discuss here first?

**Comment by SangamSwadiK** [comment]
> Great! Go for it!
> 
> Do you have an idea of how to go about it? or shall we discuss here first?

Hi, Is the book name "Feature engineering for machine learning" ?, I think ill be able to better understand and discuss about it after going through the book.

**Comment by solegalli** [comment]
This is the book:
https://www.amazon.de/-/en/Alice-Zheng/dp/1491953241

**Comment by solegalli** [comment]
Yes, that is correct :)

**Comment by SangamSwadiK** [comment]
Okay Cool !
Ill do it and submit a PR.
