### ISSUE TITLE
`WoEEncoder` should return a list with all the variables that have 0 in the denominator of the WoE

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#430]
At the moment, the transformer fails when it encounters one variable with 0 in the denominator of the WoE formula. We would like it to assess and raise an error with all the variables that show this behaviour.

**Comment by nandevers** [comment]
Hi @solegalli , do you think I could pick up this one? Please let me know.

**Comment by solegalli** [comment]
I am more than happy for you to do it @nandevers 

I think the main modification need to be done somewhere here:
https://github.com/feature-engine/feature_engine/blob/248465e111416f88a4784b5e2e13a83d47e1f00e/feature_engine/encoding/woe.py#L174-L181

**Comment by nandevers** [comment]
Awesome, working on it! Thanks a bunch

**Comment by ddofer** [comment]
Same issue when using the SelectByInformationValue - I can't use it with default settings.

`File /opt/anaconda3/envs/nlp/lib/python3.9/site-packages/feature_engine/selection/information_value.py:233, in SelectByInformationValue.fit(self, X, y)
    231 self.information_values_ = {}
    232 for var in self.variables_:
--> 233     total_pos, total_neg, woe = self._calculate_woe(X, y, var)
    234     iv = self._calculate_iv(total_pos, total_neg, woe)
    235     self.information_values_[var] = iv

File /opt/anaconda3/envs/nlp/lib/python3.9/site-packages/feature_engine/encoding/woe.py:72, in WoE._calculate_woe(self, X, y, variable, fill_value)
     70 if not (pos[:] == 0).sum() == 0 or not (neg[:] == 0).sum() == 0:
     71     if fill_value is None:
---> 72         raise ValueError(
     73             "The proportion of one of the classes for a category in "
     74             "variable {} is zero, and log of zero is not defined".format(
     75                 variable
     76             )
     77         )
     78     else:
     79         pos[pos[:] == 0] = fill_value

**ValueError: The proportion of one of the classes for a category in variable _bilirubin_ is zero, and log of zero is not defined**`

**Comment by solegalli** [comment]
Hey @ddofer this happens when a category shows only 1 of the target classes only. In general, those are infrequent categories. A solution could be to group infrequent categories before applying the selector. Check out RareLabelEncoder.

Was this a question? or a suggestion for some functionality?

Sorry for the delayed response. I was sick, then on hols, and after that catching up with accumulated work :_(

**Comment by mordechaiby** [comment]
Hi @solegalli will the problem @ddofer presented going to be solved in the future? I also encountered the same problem.

**Comment by solegalli** [comment]
Hi @mordechaiby 

What do you mean by "solved"?

If the category is infrequent, it may only show one of the target values, say 1 or 0. There is no "logical"or "mathematical" way to resolve this. Using an arbitrary value as a replacement could lead to undesired, or at least, meaningless values for that category.

A potential solution is to group infrequent labels together and treat them as one, to avoid this issue. 

Does this help?

**Comment by mordechaiby** [comment]
That seems like a viable option, or alternatively, you might consider skipping that feature. In my view, if an error occurs with a single feature, it is unfortunate for the code to crash rather than proceed to subsequent features or continue the training process.
