### ISSUE TITLE
[NEW TRANSFORMER] arcsin transformation for decimal data

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#434]
For more info on the transformation:

https://stats.stackexchange.com/questions/251449/how-do-i-find-a-variance-stabilizing-transformation

https://www.stata.com/users/njc/topichlp/transint.hlp

Creating the new class is fairly straighforward.

Use the ReciprocalTransformer() as template. Copy it into a new python script called arcsin.py and edit the fit, transform and inverse transform to return the arcsin with np.arcsin and the inverse of that (which we need to investigate how to get it).

Then, we need to adjust the docstrings with some info about the arcsin transformation, which can be found in the links above.

**Comment by Morgan-Sell** [comment]
hola @solegalli,

I'll also work on this issue! I like creating a queue of tasks.

**Comment by solegalli** [comment]
Hi @Morgan-Sell . @tomtom-95 is working on this transformer already here #444
