### ISSUE TITLE
A little typo in the document

### ISSUE THREAD

**Issue by SharkFin-top** [feature-engine/feature_engine#437]
doc link: https://feature-engine.readthedocs.io/en/1.2.x/user_guide/selection/DropHighPSIFeatures.html#case-3-split-data-based-on-time-date-as-cut-off

in this ode block:

```python
X_transformer = transformer.transform(X)

X_transformed.columns

Index(['var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'time'], dtype='object')
```

`X_transformed.columns` should be `X_transformer.columns` 

Thanks♪(･ω･)ﾉ

**Comment by solegalli** [comment]
thank you!

it is now fixed here #433
