### ISSUE TITLE
add first-timers-welcome badge to readme

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#439]
Very easy, we need a badge to show that we welcome contributions from first-timers.

The code for the badge can be taken from here:
https://www.firsttimersonly.com/

and it is actually this one:
[![first-timers-only](https://img.shields.io/badge/first--timers--only-friendly-blue.svg?style=flat-square)](https://www.firsttimersonly.com/)

**Comment by Safirangi** [comment]
Should this batch be added to the README.md after the other batches?

**Comment by solegalli** [comment]
I think so.

**Comment by solegalli** [comment]
Thank you!

**Comment by Safirangi** [comment]
Thank you for letting me to contribute!

**Comment by solegalli** [comment]
You are very welcome! Feel free to join us again :)
