### ISSUE TITLE
[ENHANCEMENT] change pandas.corr() by numpy alternative in correlation selectors

### ISSUE THREAD

**Issue by lauradang** [feature-engine/feature_engine#446]
**Is your feature request related to a problem? Please describe.**

For the following feature selectors:
- [SmartCorrelatedSelection](https://feature-engine.readthedocs.io/en/1.3.x/api_doc/selection/SmartCorrelatedSelection.html)
- [DropCorrelatedFeatures](https://feature-engine.readthedocs.io/en/1.3.x/api_doc/selection/DropCorrelatedFeatures.html)

`pandas.corr(method='pearson')` is currently being used to calculate the correlation matrix. This is very slow in performance compared to using the `numpy` equivalent method.

An example of where `pandas.corr(method='pearson')` is used can be found [here](https://github.com/feature-engine/feature_engine/blob/1b558821a58552bfb1addf96a86d04302ff619c2/feature_engine/selection/smart_correlation_selection.py#L239).

**Describe the solution you'd like**

Refer to here for specific code change: [smart_correlation_selection.py](https://github.com/feature-engine/feature_engine/blob/1b558821a58552bfb1addf96a86d04302ff619c2/feature_engine/selection/smart_correlation_selection.py#L239)

Instead of this:

```python
 _correlated_matrix = X[self.variables_].corr(method=self.method)
```

We can do this instead:

```python
if self.method == 'pearson':
    _correlated_matrix = pd.DataFrame(np.corrcoef(X[self.variables_], rowvar=False), columns=X[self.variables_].columns)
    _correlated_matrix.index = _correlated_matrix.columns
```

**Additional context**
I currently haven't looked into how to make the other methods faster (e.g.` method=spearman`), but this can also be considered in this feature.

**Comment by solegalli** [comment]
Hi @lauradang 

Thank you so much for raising the issue.

Do you have, by any chance, some code that compares the performance of the 2 (pandas.corr() vs np.corrcoef())? To have a better view of how much faster we are talking about?

We would also need to seek support for the other correlation formulas. At the moment, this transformer supports pearson, spearman, kendall and also user designed functions, which are all handled out of the box by pandas. My guess is that numpy will have something similar.
