### ISSUE TITLE
add inverse_transform method and functionality to BoxCoxTransformer

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#449]
We can use the inv_boxcox functionality from scipy.special: https://docs.scipy.org/doc/scipy-1.8.0/html-scipyorg/reference/generated/scipy.special.inv_boxcox.html

**Comment by SangamSwadiK** [comment]
@solegalli  Can I take this up ?
The link is updated to;
[https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.inv_boxcox.html](url)

**Comment by solegalli** [comment]
Absolutely! That would be great, thanks!

**Comment by SangamSwadiK** [comment]
> Absolutely! That would be great @SangamSwadiK, thanks!

@solegalli  Hi, I've submitted a PR #471 , please let me know if i'm missing anything. I'll do it asap.
