### ISSUE TITLE
mypy throws error on latest main

### ISSUE THREAD

**Issue by SangamSwadiK** [feature-engine/feature_engine#473]
**Describe the bug**
I'm following the contribution guidelines, But when I run mypy on the latest main branch, I get type errors.The type errors are not related to the issues im working on.

**To Reproduce**
1.  Pull the latest main branch.
2. Cd into feature-engine 
3. Run mypy feature_engine
4. Error must be visible in the command prompt.

**Expected behavior**
Mypy must not be giving out type errors as per guidelines

**Screenshots**
![mypy throws errors](https://user-images.githubusercontent.com/35230623/173229147-b208b27c-ff10-465c-912c-630f347f2c5b.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Google Chrome
 - Version: Chrome (102.0.5005.63), Windows 10 (19044.1706)

**Additional context**
None

**Comment by solegalli** [comment]
is this new?

I can see that the test is passing in main branch in the repo.

Did it pass before and now raises an error? or is this the first time you try?

could you please check the version of numpy and mypy that you are using and let me know?

**Comment by SangamSwadiK** [comment]
Hi, I just tried it now.
I'm using the following when I installed from requirements.txt.

- Python version: 3.10.3
- Numpy version: 1.22.4
- Pandas version: 1.4.2
- Scikit-learn version: 1.1.1
- Scipy version: 1.8.1
- Statsmodels version: 0.13.2
- Mypy version: 0.961

**Comment by SangamSwadiK** [comment]
@solegalli  I'm getting the same mypy type errors on the 1.4.X branch released 2 days ago.

**Comment by solegalli** [comment]
I can't reproduce the error in my computer :_(

How about, you make a PR with some code changes that you propose, and we see if the test passes in the PR?

@ChristopherGS any idea why this could be?

**Comment by SangamSwadiK** [comment]
The Circle CI for `Python 3.10` seems to be using `Python 3.9`
![ci-pipeline](https://user-images.githubusercontent.com/35230623/173230264-cdb617f1-b503-4650-bd1f-917bcdc3aa59.PNG)

**Comment by solegalli** [comment]
atte #474

**Comment by solegalli** [comment]
> @solegalli The Circle CI for `Python 3.10` seems to be using `Python 3.9`, could this be the problem why it is passing ? ![ci-pipeline](https://user-images.githubusercontent.com/35230623/173230264-cdb617f1-b503-4650-bd1f-917bcdc3aa59.PNG)

Well spotted thank you! Fixing in #474 but still can't manage to reproduce the error.

waiting to hear from @ChristopherGS

**Comment by solegalli** [comment]
After further investigation, this typing error is caused by numpy versions 1.21 and above.

When I installed numpy 1.22.4 I got the same error as @SangamSwadiK when executing mypy locally.
With an older version, the typing tests passed.

See for example [here](https://github.com/asyml/forte-wrappers/issues/90) and [here](https://github.com/asyml/forte-wrappers/issues/91) resolves the issue.

What puzzles me is that fixing typing as explained in the former link fixes the problem locally, but in circle ci, even though numpy version 1.22.4 seems to be installed, it says it does not have attribute `typing`.

So I am not really sure how to move on. Options are:

- we just ignore the problem so long tests pass in circleci
- we add a #type ignore in the lines raising the error
- we dig further

So this issue has 2 PRs linked #476 where I change the type for numpy typing and #474 to fix the python 3.10 tests in circle ci

**Comment by SangamSwadiK** [comment]
> After further investigation, this typing error is caused by numpy versions 1.21 and above.
> 
> When I installed numpy 1.22.4 I got the same error as @SangamSwadiK when executing mypy locally. With an older version, the typing tests passed.
> 
> See for example [here](https://github.com/asyml/forte-wrappers/issues/90) and [here](https://github.com/asyml/forte-wrappers/issues/91) resolves the issue.
> 
> What puzzles me is that fixing typing as explained in the former link fixes the problem locally, but in circle ci, even though numpy version 1.22.4 seems to be installed, it says it does not have attribute `typing`.
> 
> So I am not really sure how to move on. Options are:
> 
> * we just ignore the problem so long tests pass in circleci
> * we add a #type ignore in the lines raising the error
> * we dig further
> 
> So this issue has 2 PRs linked #476 where I change the type for numpy typing and #474 to fix the python 3.10 tests in circle ci

Hi @solegalli , if the return type is `np.ndarray` The tests for array seem to be passing mypy.
I've checked the numpy repo on github for similar issues and couldnt find any.

I'm currently going through.
https://numpy.org/devdocs/reference/typing.html

I guess we can restrict the numpy versions if nothing else works out.

**Comment by solegalli** [comment]
Hi @SangamSwadiK thank you. Good pointer. I removed typing and change array for ndarray and the tests pass both locally and in circleci.

Also have this question in stackoverflow:
https://stackoverflow.com/questions/72599663/numpy-typing-works-locally-but-not-in-circleci?noredirect=1#comment128244278_72599663

to try and understand a bit more.

**Comment by SangamSwadiK** [comment]
> Hi @SangamSwadiK thank you. Good pointer. I removed typing and changed` array` for `ndarray` and the tests pass both locally and in circleci.
> 
> Also have this question in stackoverflow: https://stackoverflow.com/questions/72599663/numpy-typing-works-locally-but-not-in-circleci?noredirect=1#comment128244278_72599663
> 
> to try and understand a bit more.

Yes, In the numpy docs
https://numpy.org/devdocs/reference/typing.html

They ask us to add a separate configuration for typing in mypy. for numpy
`[mypy]
plugins = numpy.typing.mypy_plugin`

It says `np.ArrayLike` can also be used for typing.
