### ISSUE TITLE
Adding auto threshold to DropHighPSIFeatures

### ISSUE THREAD

**Issue by GLevV** [feature-engine/feature_engine#494]
**Is your feature request related to a problem? Please describe.**
Staple thresholds 0.1 and 0.25 are empirical, but there are alternatives to calculate threshold based on data and parameters of the transformation

**Describe the solution you'd like**
There are two formulas [described in this dissertation](https://scholarworks.wmich.edu/cgi/viewcontent.cgi?article=4249&context=dissertations) to calculate psi threshold from number of bins and number of datapoints in base and test datasets. From my experiments Chi2(0.999, bins) works best. We could keep default parameter as 0.25, but also provide 'auto' option.

**Comment by solegalli** [comment]
Thanks @GLevV for the suggestion.

@gverbock what do you think about this?

**Comment by gverbock** [comment]
I like the idea to use the number of points to set a common threshold for all features. On the other hand the number of bins is arbitrary so it there will be an arbitrary factor anyway (still need to read the dissertation on that topic). @GLevV  what is your view on this?

**Comment by GLevV** [comment]
Yes, threshold will depend on size of dataset (and on `split_frac`)  and number of bins, which kinda makes sense. In practice it gives lower thresholds than 0.1 or 0.25, but we could keep the defaults as is.

Should be pretty straightforward to implement, I think

**Comment by solegalli** [comment]
@GLevV would you like to give it a go?

**Comment by GLevV** [comment]
@solegalli ye, why not

**Comment by GLevV** [comment]
closed with #498
