### ISSUE TITLE
replace loop by broadcasting in cyclical features

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#513]
The class creates features in a loop:

https://github.com/feature-engine/feature_engine/blob/9d4b67e34973fb0dad6a1df6ba88a3305a2c5bb7/feature_engine/creation/cyclical_features.py#L151-L154

I think we could replace that by broadcasting and make it faster

**Comment by solegalli** [comment]
Hi @GLevV

You are really good at programming,  so I thought I would pick your brain once more :)

Would it be possible to replace this loop by array / pandas operations? and if yes, would you be able to give it a go?

I think you should be able to obtain the variable names from the get_feature_names_out() method passing the input variables

**Comment by GLevV** [comment]
Will look into it

**Comment by GLevV** [comment]
In this case loop is faster, see PR

**Comment by solegalli** [comment]
Thank you @GLevV 

this was really helpful. I'll close the issue then !
