### ISSUE TITLE
Cyclical datetime feature transformation

### ISSUE THREAD

**Issue by Morgan-Sell** [feature-engine/feature_engine#527]
**Is your feature request related to a problem? Please describe.**
Some date/time features have cyclical trends, e.g., solar and wind energy generation. Let's create a transformer that can capture cyclical trends.

This [Medium post](https://medium.com/ai%C2%B3-theory-practice-business/top-6-errors-novice-machine-learning-engineers-make-e82273d394db) claims that such features are transformed in such a manner that omits this trend/relationship.

**Describe the solution you'd like**
Create a transformer that evaluates cyclical date/time relationships and transforms the feature properly.

**Describe alternatives you've considered**
N/A

**Additional context**
Website explaining topic: http://blog.davidkaleko.com/feature-engineering-cyclical-features.html

**Comment by solegalli** [comment]
Is this not covered by the CyclicalFeatures class?

**Comment by solegalli** [comment]
I reckon we can close this issue. If CyclicalFeatures does not have the functionality requested already, we can open it again :)
