### ISSUE TITLE
Applying multiple transformations on the same variable

### ISSUE THREAD

**Issue by david-cortes** [feature-engine/feature_engine#529]
Oftentimes, one wants to create multiple transformations out of a single column, or to have the original column in addition to the transformations.

For example, I might have a categorical column for which I might want to do something as follows:
* Impute missing values.
* Create a frequency-encoded version of the column.
* Create a mean-encoded version of the column.
* Apply the rare label transformer.

And obtain 3 columns as output.

This is currently rather inconvenient to do as one has to create a new transformer that would concatenate multiple versions of the same column to pass them to transformers further down a pipeline.

**Comment by solegalli** [comment]
Hi @david-cortes 

Thank you for the suggestion.

These are my thoughts:

The encoding methods are kind of tailored to the model we want to train. For example, OrdinalEncoding works with decision trees, but not really with linear models, unless we order following the target value. One Hot encoding is on the other hand more suitable for linear models, but not really for decision trees as it expands the feature space.

Encoding with WoE, trees, target mean or ordered ordinal encoding, would, in theory, return correlated features. So I don't see, at first sight, the value of having the variables encoded with all these procedures at the same time. Instead, if unsure of which encoding is best, this could be found with cross-validation.

But maybe I am missing something. @david-cortes In which situation would you want to have the variables encoded with multiple methods?

@GLevV what's your view on this?

**Comment by GLevV** [comment]
Yes, this one needs clearly defined usecase and example before any decision could be made

**Comment by david-cortes** [comment]
For example, one use case would be if there is a high-cardinality categorical variable in which a handful categories are more common than the rest, from which one might want to create both a rare-label+dummy-encoded that leaves only top-5 or so and additionally a weight-of-evidence and/or frequency-encoded version of it, and pass those further down the line to either a linear model or to a decision tree model that doesn't support categorical features, such as scikit-learn's. Even though this might introduce some correlation (particularly for frequency encoding), the results out of such models are typically better than when applying a single transformation.

Another use case is if for example there are a large number of numerical variables, and one doesn't know apriori which kind of transformations are better for each, so one tries out several by creating a single data frame that concatenates them and then applies some further feature selection techniques on that.

**Comment by solegalli** [comment]
I think we are not going to move forward with this one, for the time being, because it seems too specific.

We can open it later if it gathers users support.
