### ISSUE TITLE
String Similarity Encoder

### ISSUE THREAD

**Issue by GLevV** [feature-engine/feature_engine#530]
Recently dirty_cat dropped support for edit distances and left only ngram similarity, so I think it's time to add encoder like this.
The whole concept is pretty simple: instead of encoding categories if there is an exact match like OneHotEncoder, we encode categories based on their string similarity. It's very useful if dataset has 'dirty' (poorly-defined) categories (for example, professions). Since only very few libraries have something like that, it could be beneficial to add it here.

Proposition:
Add StringSimilarityEncoder with only basic functionality for now, i.e. support one similarity measure (gestalt pattern matching will do, it's from standard library so it will be fast and no additional dependencies required) and only 'most_frequent' categories, i.e. just like OneHotEncoder we encode all or top-k categories in the variable, no kmeans method for finding prototypes for now.

[dirty_cat similarity encoder](https://dirty-cat.github.io/stable/generated/dirty_cat.SimilarityEncoder.html), [twds article](https://towardsdatascience.com/similarity-encoding-for-dirty-categories-using-dirty-cat-d9f0b581a552)

**Comment by solegalli** [comment]
Thank you for so much detail @GLevV.

Go for it :)

This article about dirty categories has been in my "to read" list for quite a long time now :p
