### ISSUE TITLE
add code snippet of class use to API

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#534]
Users like copying and pasting the code for simplicity.

Modules

- [x] creation
- [x] datetime
- [x] discretisation
- [x] imputation
- [x] encoding
- [x] outliers
- [x] preprocessing
- [x] selection
- [x] timeseries
- [x] transformation
- [x] wrappers

Adding all relevant PRs:

https://github.com/feature-engine/feature_engine/pull/564
https://github.com/feature-engine/feature_engine/pull/563
https://github.com/feature-engine/feature_engine/pull/560
https://github.com/feature-engine/feature_engine/pull/547
https://github.com/feature-engine/feature_engine/pull/582
https://github.com/feature-engine/feature_engine/pull/647
https://github.com/feature-engine/feature_engine/pull/644
https://github.com/feature-engine/feature_engine/pull/646
https://github.com/feature-engine/feature_engine/pull/643

**Comment by datacubeR** [comment]
@solegalli I think I could work on this one too? Would you give me some guidelines on how to address this one?

**Comment by solegalli** [comment]
I've received feedback from some users, telling me that it would be nice to have a snippet of code implementing the transformer in the API part of the docs, where we describe the parameters, so that they can do copy and paste  and execute.

So the task here would be, for every class in feature_engine, in the docstrings, create a mini toy dataset, and apply the transformer. 

We could break this issue down into multiple PRs, one for each module, so it does not become a monster issue :)

**Comment by datacubeR** [comment]
@solegalli 
It should something like this?  I will start on this one too... 

https://github.com/scikit-learn/scikit-learn/blob/36958fb240fbe435673a9e3c52e769f01f36bec0/sklearn/linear_model/_logistic.py#L1011-L1024

**Comment by solegalli** [comment]
yes, that is it :)

thank you!

**Comment by solegalli** [comment]
Related PRs:

#564 
#563 
#560
#547

**Comment by solegalli** [comment]
@Morgan-Sell this is a documentation issue that also needs support. It consist of adding a code-snippet in the API docstrings, so that users can copy and paste. 

We are doing 1 PR per module. @datacubeR did the ticked modules already. But we have several modules to go, so if you guys have some time in your hands, open a PR and tag it here, so we know who is working on which module.

Thanks a lot!

**Comment by Morgan-Sell** [comment]
@solegalli, I'll add this to my queue. I'm going to focus on issues #571 and #292 for now ;)

**Comment by Morgan-Sell** [comment]
@solegalli,

Have we completed this PR? I'm spot-checking class user guides for the non-checked modules, e.g., outlier, preprocessing, and selection. I see code snippets in the user guide.

**Comment by datacubeR** [comment]
I think I've added those. There is a couple I haven't addressed yet such as timeseries. I can check the missing ones and finish them this weekend if you like...

**Comment by Morgan-Sell** [comment]
@datacubeR 

Go for it, Alfonso! You can take it all - you're doing a great job. This is a fundamental enhancement for feature-engine.

**Comment by datacubeR** [comment]
@solegalli I was checking your checklist and looking at the documentation the Selection module is not reflecting code examples, but they are already integrated into main. Can you take a look if you already built that documentation or if it was added to the release?

So far I added another PR #643 with more examples and I'm working on the remaining ones...

**Comment by solegalli** [comment]
Hey @datacubeR 

Your new PRs cover all the remaining examples. Thank you so much!

When we merge those, we can close this issue!

The examples for the selection module are indeed in main, so I ticked them here. And I already had that included in the what's new file for next release #617 

So we are almost good to go with this issue and the new release.

**Comment by datacubeR** [comment]
@solegalli All the PRs are fixed as per your suggestions...
