### ISSUE TITLE
add parameter to handle NA as per pandas functionality in forecasting classes

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#536]
pandas shift and pandas rolling have a parameter to handle NaN introduced during the operations, we should allow users to tap into that parameter in our transformers.

@KishManani one for you? :p

Should be an easy fix.

**Comment by solegalli** [comment]
Hi @Morgan-Sell this issue, has your name on it :p

We need to add a parameter in the init of the LagFeatures, WindowFeatures and ExpandedWindowFeatures that then would be passed onto the fill_value parameter of pandas.shift (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shift.html) to replace the nan introduced by that value.

Small code modification, plus a test or two per class :)

**Comment by Morgan-Sell** [comment]
Dale!

**Comment by solegalli** [comment]
I think that is actually a good idea. Go for it :)
