### ISSUE TITLE
Bug: MatchCategories cannot import 

### ISSUE THREAD

**Issue by px39n** [feature-engine/feature_engine#557]
ImportError                               Traceback (most recent call last)
[<ipython-input-21-d13d6f98bc57>](https://localhost:8080/#) in <module>
      1 get_ipython().system('pip install feature_engine')
----> 2 from feature_engine.preprocessing import MatchCategories
      3 match_categories = MatchCategories(missing_values="ignore")
ImportError: cannot import name 'MatchCategories' from 'feature_engine.preprocessing' (/usr/local/lib/python3.7/dist-packages/feature_engine/preprocessing/__init__.py)

Hi, the following code is not working in google colab

```
!pip install feature_engine
from feature_engine.preprocessing import MatchCategories
```

**Comment by solegalli** [comment]
Could you corroborate the version of feature engine that is being installed?

```
import feature_engine
feature_engine.__version__
```

It should be 1.5.0 or above.

**Comment by px39n** [comment]
> Could you corroborate the version of feature engine that is being installed?
> 
> ```
> import feature_engine
> feature_engine.__version__
> ```
> 
> It should be 1.5.0 or above.

yes its 1.4.0 thanks for reply
