### ISSUE TITLE
When a variable is not present in the data, our error message does not inform which variables are those.

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#571]
Pandas does.

So if X[var1, var2, var3] and var3 not in X, then pandas error says which variable is not. Our variable manipulation functions do not.

I think we should probably rely this task to pandas. We basically need to adjust our functions to check variables.

**Comment by Morgan-Sell** [comment]
@solegalli, yes, I agree!

I'll work on this issue and the Random Noise Selector (#292).
