### ISSUE TITLE
RelativeFeatures: add option not to fail when dividing by zero and instead fill inf values with something

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#577]

**Comment by Morgan-Sell** [comment]
hola @solegalli,

Do we want to create an init param, e.g., `fill_value` that would be used when `div` is selected for the `func` param?

The `fill_value` will replace be applied when a value is divided by zero. This logic will be applied to the `_div()` method, which is below.

```
def _div(self, X):
        for reference in self.reference:
            if (X[reference] == 0).any():
                raise ValueError(
                    "Some of the reference variables contain 0 as values. Check and "
                    "remove those before using this transformer."
                )
            varname = [f"{var}_div_{reference}" for var in self.variables]
            X[varname] = X[self.variables].div(X[reference], axis=0)
        return X
```

**Comment by solegalli** [comment]
We could. 

Not sure fill_value is the right name because that is commonly use for NaN. But can't think of a better name now.

Will this be your new task? :)

**Comment by Morgan-Sell** [comment]
yes, I'll complete this task and I'll think of a new param name. Another question...

When `fill_value` is `None`, should we raise the existing error? And, should `None` be the default value?

**Comment by solegalli** [comment]
yes, and yes :)
