### ISSUE TITLE
allow One hot encoder to work with nan

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#587]
At the moment the one hot encoder does not support missing values. It will raise an error. We want to make this transformer more versatile.

OneHotEncoder could have 3 options:

- [ ] missing_values="raise" ==> current functionality
- [ ] missing_values="encode" ==> treat na as an additional category
- [ ] missing_values="ignore" ==> ignore, but only if encoding in k-1, otherwise they will be merged with the dropped category

**Comment by SunnyxBd** [comment]
started working on this one :)

**Comment by solegalli** [comment]
Awesome. 

There is a PR, #572, that changes the logic of the encoders, and adds lots of tests. Please checkout that branch to make modifications to the OHE for this PR.

Or alternatively, wait till I merge, will take me a few days :)

**Comment by solegalli** [comment]
PR is now merged!

**Comment by SunnyxBd** [comment]
Cool, thank you!!

**Comment by SunnyxBd** [comment]
Thinking about how to add '`encode`' to the list of accepted `missing_values` argument in `_init_`. 🤔🤔

**Comment by solegalli** [comment]
We've done it for other classes. I paste here the relevant lines:

https://github.com/feature-engine/feature_engine/blob/a0106c968b14922d5123aaf51625fa66123dfad8/feature_engine/encoding/count_frequency.py#L156

https://github.com/feature-engine/feature_engine/blob/a0106c968b14922d5123aaf51625fa66123dfad8/feature_engine/encoding/count_frequency.py#L167

See for example this transformer:
https://github.com/feature-engine/feature_engine/blob/main/feature_engine/encoding/count_frequency.py#L167

**Comment by solegalli** [comment]
wonfix
