### ISSUE TITLE
SmartCorrelatedSelection inconsistency in features to drop

### ISSUE THREAD

**Issue by vm885032** [feature-engine/feature_engine#684]
**Describe the bug**
The SmartCorrelatedSelection from feature engine version 1.5.2 is not reproducing the same result after I restart the kernel. I have done a dummy test on the titanic dataset where one hot encoding has been done and then I am searching for the correlated features to drop using the variance method from the documentation.

**Screenshots**
In the initial run of the notebook, I get the following results:

![image](https://github.com/feature-engine/feature_engine/assets/123634410/aade8389-8342-4cf3-bcd5-b0645a985d03)

After restarting and re-running the notebook, I get a second set of results as follows:

![image](https://github.com/feature-engine/feature_engine/assets/123634410/31e550ee-2a27-445c-af57-63d7093aaff3)

I have ensured that "encoded_data" is the same reproducible dataset after restarting the kernel, the transformers used here are the ones from feature_engine to impute and encode respectively.

**Comment by solegalli** [comment]
Thank you for the details. Would you be able to provide a link to the notebook? or upload the notebook? or copy and paste the entire notebook? I need to see how encoded_data is being generated.

Thank you!

**Comment by vm885032** [comment]
![image](https://github.com/feature-engine/feature_engine/assets/123634410/9fa3cc3e-c36e-467b-8b0e-37d9080dfb97)
![image](https://github.com/feature-engine/feature_engine/assets/123634410/e6258f90-d3f7-414d-9d49-2b5ef0c3bb70)
![image](https://github.com/feature-engine/feature_engine/assets/123634410/a2818150-9dbf-4bd1-b1df-8f48c66f0e9b)
![image](https://github.com/feature-engine/feature_engine/assets/123634410/4107f74f-a759-4198-b2f9-4bceac9ad2f6)

**Comment by solegalli** [comment]
Thank you very much @vm885032 !!

I will look into this as soon as I find a minute.

**Comment by solegalli** [comment]
Some initial research suggests that the order changes when converting to sets and then back to lists.

We need a better implementation of the correlation selectors.

**Comment by solegalli** [comment]
similar to #570
