### ISSUE TITLE
Parametrize unseen for the OrdinalEncoder in DecisionTreeEncoder

### ISSUE THREAD

**Issue by 93lorenzo** [feature-engine/feature_engine#728]
I started to use the [DecisionTreeEncoder](https://github.com/feature-engine/feature_engine/blob/main/feature_engine/encoding/decision_tree.py) for categorical variables. Lately I ran into an exception and I found out it was about when in there is an unseen category. 
I understand this as a default behaviour, but I was thinking that having the flexibility to decide that in the constructor can be helpful.   

To give more context:
From [the code](https://github.com/feature-engine/feature_engine/blob/main/feature_engine/encoding/decision_tree.py#L245) I saw that the `OrdinalEncoder` has by default the unseen variable set to `"raise"`
```python 
        cat_encoder = OrdinalEncoder(
            encoding_method=self.encoding_method,
            variables=variables_,
            missing_values="raise",
            ignore_format=self.ignore_format,
            unseen="raise",
        )
```
**Suggestion**

I would like to suggest to make that param something more flexible having it in the constructor 
```python 
     
    def __init__(
        self,
        encoding_method: str = "arbitrary",
        cv=3,
        scoring: str = "neg_mean_squared_error",
        param_grid: Optional[dict] = None,
        regression: bool = True,
        random_state: Optional[int] = None,
        variables: Union[None, int, str, List[Union[str, int]]] = None,
        ignore_format: bool = False,
        # added var
        unseen: str = 'raise',
    ) -> None:

        super().__init__(variables, ignore_format)
        self.encoding_method = encoding_method
        self.cv = cv
        self.scoring = scoring
        self.regression = regression
        self.param_grid = param_grid
        self.random_state = random_state
        self.unseen = unseen


[ ... other code ...]



   cat_encoder = OrdinalEncoder(
            encoding_method=self.encoding_method,
            variables=variables_,
            missing_values="raise",
            ignore_format=self.ignore_format,
            unseen=self.unseen,
        )
```

Of course there are alternatives, in my project I am currently overriding the function to take into account that behaviour, but I think that this flexibility might help others .
In case it is found a reasonable change I would be happy to help on making the change

**Comment by glevv** [comment]
Sounds reasonable to me.

I will check if it's doable and get back to you.

**Comment by solegalli** [comment]
I am not sure I understand the suggestion or the problem. At the moment, we offer options about what to do with unseen categories. What's wrong with that functionality? What else would the transformer need to do?

The init parameters need to be immutable to be compatible with the sklearn API, so we can't really add functionality there, we need to accept them as the user enters them.

Anyhow, I am sure I am missing something here, so would be great if you guys could enlighten me :)

**Comment by glevv** [comment]
DecisionTreeEncoder does not expose "unseen" argument to the user and instead uses constant value "raise". Proposition is to expose it to the user.

**Comment by 93lorenzo** [comment]
First of all, thanks a lot for the comments! 🙏 
I will try to explain more about why I raised this this issue. 

I was using the transformer in a training pipeline.  When there was an unseen category in one of the split, it was throwing the error related due to one of categories was unseen. 

* Exploring to the code I noticed that, this was happening because the OrdinalEncoder in the fit of the `DecisionTreeEncoder` has by default 'raise'. 
* That is why I was thinking that might be exposing the "unseen" argument can help in such cases when somebody wants to use a different than 'raise' in the OrdinalEncoder that is in the fit method.

**Comment by solegalli** [comment]
Sorry, I get it know. I forgot that we do not expose that in the TreeEncoder.. By all means, we should certainly change that! If any of you wants to volunteer, that'd be a major help!
Thank you!

**Comment by 93lorenzo** [comment]
Thanks!! I volunteer, I will do an PR this week

**Comment by 93lorenzo** [comment]
Hello there! 
I created the [PR](https://github.com/feature-engine/feature_engine/pull/729) for this change !

To make the tests successful I had to change also ` tests/test_selection/test_single_feature_performance.py `

Please have a look and let me know if there is anything to change or adjust! :)
