### ISSUE TITLE
create CONTRIBUTING.md

### ISSUE THREAD

**Issue by MetroCat69** [feature-engine/feature_engine#735]
Maybe we can create a CONTRIBUTING.md file explaining stuff about the project structure and how for example you should create a new transformer. I am new to this project so I don't feel qualified

**Comment by solegalli** [comment]
We have contributing guidelines in the docs: https://feature-engine.trainindata.com/en/latest/contribute/index.html

I think it's fair to find it intimidating. 

My suggestion would be: if you want to create a new selector class, which I think it's what you do from our discussion in a different issue, take any selector class that already exits and use it as template. I think that for MRMR, you can take the correlation selector, and then replace the fit and transform methods with the new logic. And we take it from there.

I can point you in the right direction all along.

Hope that helps
Cheers
