### ISSUE TITLE
allow outlier trimmer and winsorizer to select optimal fold automatically based on the method to detect outliers

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#754]
At the moment, the parameter fold from OutlierTrimmer and Winsorizer are set to 3. 

I'd like it to be set to "auto" which would have this behaviour:

- if iqr: then fold = 1.5
- if gaussian, then fold=3
- if MAD, then fold=3.29 (coincides with r package: https://easystats.github.io/performance/articles/check_outliers
- if quantile: then 0.05

Easy fix, plus tests.

**Comment by solegalli** [comment]
@glevv could I tempt you with this one?

**Comment by glevv** [comment]
> @glevv could I tempt you with this one?

Will look into it
