### ISSUE TITLE
transformer to apply mean normalization

### ISSUE THREAD

**Issue by solegalli** [feature-engine/feature_engine#763]
in mean normalization, we subtract the mean from each value and then divide by the value range. This centres the variables at 0, and scales their values between -1 and 1. It is an alternative to standardization.

sklearn has no transformer to apply mean normalization. but we can combine the standard scaler and the robust scaler to do so. The thing is, that both transformers need to be fit over the raw data, so we can't use them within a pipeline, because the pipeline applies the transformation before the next transformer learns the required parameters.

My idea is to wrap both transformers within a class, so that fit is applied without transform, and then with those parameters, we can transform the data. See for example here: https://github.com/solegalli/Python-Feature-Engineering-Cookbook-Second-Edition/blob/main/ch07-scaling/Recipe-4-mean-normalization.ipynb

**Comment by VascoSch92** [comment]
Instead of wrapping two transformers within a class, could also be an idea to create a brand new transformer which accomplish mean normalisation?

I understand that this could create some duplicated code, but on the other hand, the new mean normalisation transformer will be easy to understand and to debug.

I'm just thinking :-)

**Comment by solegalli** [comment]
Yes, it's perhaps a better idea.

**Comment by solegalli** [comment]
By any chance, would you like to give this one a go? creating a new class? and a new module. We don't have a module for scaling yet. @VascoSch92

**Comment by VascoSch92** [comment]
Yes I can give it a try :-) 

Just a little summary (please correct me if I'm wrong):
1. the idea is to create a new module scaling which contains transformers to scale columns
2. the first of these transformers will be the mean_normalization transformer right?


On a side note: there is still this [PR](https://github.com/feature-engine/feature_engine/pull/694) on the distance transformer which attend a review :-) I corrected it and now should be better. Of course, if you have time :-D

**Comment by solegalli** [comment]
Closing as completed
