### ISSUE TITLE
Sklearn Pipeline breaks

### ISSUE THREAD

**Issue by AmMoPy** [feature-engine/feature_engine#812]
**Describe the bug**

If previous steps in a pipeline produced `ndarray` while data is originally a `DataFrame`, input validation breaks if untransformed `variables` were specified at next step transformer initialization as  `check_numerical_variables()` will be triggered instead of  `find_numerical_variables()` . For example, in  `WinsorizerBase`  the  `check_X`  in `fit` method will generate new feature names that contradicts with  input `variables` as it thinks `X` is an  `ndarray`.

**To Reproduce**

```
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from feature_engine import outliers as olrs
from feature_engine.wrappers import SklearnTransformerWrapper
from scipy import stats
import pandas as pd
import lightgbm as lgb

random_state = 45

df = pd.DataFrame({
    'feat_1': stats.norm.rvs(size = 300, random_state = random_state),
    'feat_2': stats.uniform.rvs(size = 300, random_state = random_state),
    't_1': stats.lognorm.rvs(size = 300, s = 1, random_state = 40),
})

train_df, test_df = train_test_split(df, train_size = .7, random_state = random_state)
feats = df.columns[:2]
tar = 't_1'

poly = PolynomialFeatures(degree = 3)
skw = SklearnTransformerWrapper(poly)
winso = olrs.Winsorizer(
    capping_method = 'gaussian', 
    tail = 'both',  
    variables = feats.to_list(), # wrong variables disregarding previous transformation step
) 
model = lgb.LGBMRegressor(verbose = -1, random_state = random_state)

pl = Pipeline([
    ('pf', poly), # could be any transformer not supported by `SklearnTransformerWrapper`
#   ('skw', skw), # also breaks the pipeline
    ('olrs', winso),
    ('LGBM', model)
])

pl.fit(train_df[feats], train_df[tar])
```

```
>>> KeyError: "None of [Index(['feat_1', 'feat_2'], dtype='object')] are in the [columns]"
```

**Error source**

For the previous example: `fit` method in `WinsorizerBase` as `winso` should have been initialized with correct variable names or `None` 

```
if self.variables is None:
    self.variables_ = find_numerical_variables(X)
else: 
    self.variables_ = check_numerical_variables(X, self.variables) # is not a `dataframe` because of `pf` step, thus `X[variables]` fails.
```

**Possible solution**

Add checks to trigger first condition in `fit` method

```
chk_cols = '|'.join([f"x{i}" for i in range(X.shape[1])]) # Columns generated by `check_X`
if self.variables is None or any(X.columns.str.contains(chk_cols)): # updated condition
    self.variables_ = find_numerical_variables(X)
else:
    self.variables_ = check_numerical_variables(X, self.variables)
```

**Comment by solegalli** [comment]
Hey @AmMoPy 

If you change the pipeline to the following:

```
pl = Pipeline([
    ('pf', skw), # could be any transformer not supported by `SklearnTransformerWrapper`
#   ('skw', skw), # also breaks the pipeline
    ('olrs', winso),
])
```

then it works. There, instead of passing sklearn class, I passed it wrapped by feature-engine's wrapper that returns a dataframe with the correct variable names.

Alternatively, you need to make sklearn return pandas dataframes, so it keeps the variable names. So for example this would also work:

```
**poly = PolynomialFeatures(degree = 3).set_output(transform="pandas")
winso = olrs.Winsorizer(
    capping_method = 'gaussian', 
    tail = 'both',  
    variables = feats.to_list(), # wrong variables disregarding previous transformation step
) 

pl = Pipeline([
    ('pf', poly), # could be any transformer not supported by `SklearnTransformerWrapper`
#   ('skw', skw), # also breaks the pipeline
    ('olrs', winso),
])

pl.fit(train_df[feats], train_df[tar])
```

If you leave sklearn classes to return numpy arrays, then it will lose the variable name information. Feature engine will work by taking that array and assigning variable names arbitrarily. So feats.to_list() would have to contain the new feature names, which can be inferred from how feature-engine handles arrays: https://github.com/feature-engine/feature_engine/blob/3dcc864daf2bfe678b0d576dcd303e43cac5c6b5/feature_engine/dataframe_checks.py#L73

let me know if this helps, and I appreciate that the time I took to reply is not an amazing experience, sorry about that.

**Comment by AmMoPy** [comment]
> let me know if this helps, and I appreciate that the time I took to reply is not an amazing experience, sorry about 


No worries I already learned alot from your book and library and this is the appropriate time to say Thank You!

> There, instead of passing sklearn class, I passed it wrapped by feature-engine's wrapper that returns a dataframe with the correct variable names.

Indeed, I came across this issue working on my own transformer class and was testing for solutions outside Sklearn realm, when users are not mindful enough of whats going into the pipeline.

> poly = PolynomialFeatures(degree = 3).set_output(transform="pandas")

Thats actaully new to me, kudos to you!

**Comment by solegalli** [comment]
Thank you @AmMoPy that's very nice to hear :)

Hope you continue enjoying feature-engine and programming. Till next time!
