### ISSUE TITLE
DecisionTreeEncoder default value mismatch with Docs

### ISSUE THREAD

**Issue by michaelrussell4** [feature-engine/feature_engine#819]
**Description**

Very minor change. Just changing a default parameter value that was mistakenly set to 'raise' when it should have been 'ignore'.

The [documentation](https://feature-engine.trainindata.com/en/latest/user_guide/encoding/DecisionTreeEncoder.html) states that for the `DecisionTreeEncoder` the default value for the `unseen` parameter is 'ignore' but this is inconsistent with the source code which has this default parameter set to 'raise', In order to be consistent with the documentation and the [_docstrings/init_parameters/encoders.py _unseen_docstring](https://github.com/feature-engine/feature_engine/blob/ca286186f90a8661cbdbbe5cc8faed5cd90fc565/feature_engine/_docstrings/init_parameters/encoders.py) value, the code should be updated to set this parameter to 'ignore' instead of 'raise'.

I noticed this error because I included the `DecisionTreeEncoder` in my pipeline and fitted the pipeline with my training data and then when I tried to work with test data, which included unseen values, this step raised an error, which is what it should do if `unseen` is set to 'raise' but not if it was set to what the documentation stated.

**Screenshots**
![image](https://github.com/user-attachments/assets/0c96b2d4-8ffb-4a53-a65d-3bea7014100b)

**Comment by solegalli** [comment]
Thank you for raising the issue and fixing it @michaelrussell4 !
